services:
  dynamodb:
    image: amazon/dynamodb-local@sha256:d89f8fcc6b1a39cb35976c248ed42a28c66ae00dc043099210f5571e42648ab4
    command:
      - -jar
      - DynamoDBLocal.jar
      - -inMemory
      - -sharedDb
    ports:
      - "127.0.0.1:${DYNAMODB_LOCAL_PORT:-18000}:8000"
